export const products = [
  {
    id: 1,
    title: "Logoipsum IPL", // product title
    price: 99.99, // per item
    count: 5,
    imageUrl: "./product.png",
    displayMode: "each", // or 'each'
  },
  // You can add more products here too
];

export const SWAP_CONTACT_AND_PAYMENT = false; // or false to swap layout positions;

export const buttonColor = "green"; // Change this value to "red", "green", or "blue"

export const whySectionData = [
  {
    imgSrc: "./cashbackDesktop.svg",
    title: "90 Day Money Back Guarantee",
    paragraph:
      "We love our products and we're confident you will too! If you're not in love with your LogoIpsum product, our easy return and refund policy is designed to make things as easy as possible for you.",
  },
  {
    imgSrc: "./ratingDesktop.svg",
    title: "Over 75,000+ Happy Customer",
    paragraph:
      "Everyone that tries LogoIpsum says it’s a must-have. We invest a lot of love and care into making our products, so you can enjoy seeing results when using it.",
  },
  {
    imgSrc: "./customerServiceMobile.svg",
    title: "Professional Customer Support",
    paragraph:
      "Our customer service works 24/7 for your satisfaction. Feel free to reach out to us anytime.",
  },
];

export const paymentImages = [
  { src: "./visa.svg", alt: "Visa" },
  { src: "./masterCard.svg", alt: "MasterCard" },
  { src: "./amex.svg", alt: "American Express" },
  { src: "./dinnersClub.svg", alt: "Diners Club" },
  { src: "./others.svg", alt: "Other Payment Methods" },
];

export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor (Timor-Leste)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "United States",
];
